apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: form-demo
build:
  artifacts:
  - image: cxm-dev.docker.repositories.sap.ondemand.com/cxm/formdemo-ui-dev
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/form-demo.yaml
    - k8s/formdemo-load-balancer-service.yaml
