apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: formdemo-ui-dev
  name: formdemo-ui-dev
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: formdemo-ui-dev
